# Generated by Django 3.2.11 on 2022-02-01 19:14

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('shipping_method', models.CharField(max_length=255, verbose_name='Shipping Method')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('shipping_class', models.CharField(choices=[('unspecified', 'Unspecified'), ('business', 'Business'), ('economy', 'Economy')], default='unspecified', max_length=20, verbose_name='Shipping Class')),
                ('refs', models.CharField(max_length=255, verbose_name='Refs')),
                ('weights', models.CharField(max_length=255, verbose_name='Weights')),
                ('total_weight', models.CharField(max_length=255, verbose_name='Total Weight')),
                ('balance', models.CharField(max_length=255, verbose_name='Balance')),
                ('payment', models.CharField(max_length=255, verbose_name='Payment')),
                ('sender_name', models.CharField(max_length=255, verbose_name='Sender Name')),
                ('sender_address', models.TextField(verbose_name='Sender Address')),
                ('sender_mobile', models.CharField(max_length=20, verbose_name='Sender Mobile')),
                ('sender_email', models.CharField(max_length=255, verbose_name='Sender Email')),
                ('sender_notes', models.TextField(blank=True, verbose_name='Sender Notes')),
                ('reciever_name', models.CharField(max_length=255, verbose_name='Receiver Name')),
                ('reciever_address', models.TextField(verbose_name='Receiver Address')),
                ('reciever_mobile', models.CharField(max_length=20, verbose_name='Receiver Mobile')),
                ('reciever_email', models.CharField(max_length=255, verbose_name='Receiver Email')),
                ('reciever_notes', models.TextField(blank=True, verbose_name='Receiver Notes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
